### PR TITLE
Return the list of signed headers.

### LINKED ISSUE #8: Return the list of signed headers with other results.
**Is your feature request related to a problem? Please describe.**
After checking a DKIM signature and finding that results.status.result === "pass" how can I find out what headers were signed?
I would like to know which headers I can now trust, and which I might treat with skepticism.

**Describe the solution you'd like**
I would like the list of headers returned.

**Describe alternatives you've considered**
The alternative is for me to search for and parse this signature myself, I guess.

**Additional context**

### PR DESCRIPTION
**Pull request by gene-hightower**
resolve #8

### CODE REVIEW

**Comment by andris9** [comment]
Have you considered that an email message might have a multiple headers with the same key but only one of these might signed? With this approach you do not know which one is the signed header and which is not.

**Comment by gene-hightower** [comment]
This particular change might not be the best way to accomplish what I need, but some way to get the headers signed by each signature is required for my application.
Can you please suggest a method?

**Comment by gene-hightower** [comment]
<https://tools.wordtothewise.com/rfc/6376#section-5.4.2>
This should allow me to figure out which of the header field instances are the signed ones, no?
In my use case I'm interested in the To: header (and CC: and BCC:) which should have at most a single copy per message.

**Comment by andris9** [comment]
See https://github.com/postalsys/mailauth/issues/8#issuecomment-1015166005

**Pull request closed without merging**
